---
- name: Converge
  hosts: all
  vars:
    sysctl_defaults:
      - name: net.ipv4.ip_forward
        value: '1'
      - name: net.ipv6.conf.all.forwarding
        value: '1'
      - name: kernel.panic
        value: '10'
  roles:
    - role: rolehippie.sysctl

...
